LuteOrg/lute-v3

lute/db/demo/languages/russian.yaml

These are the settings I've used for Russian

Created russian.yaml file

---

lute/db/demo/languages/hindi.yaml
lute/db/demo/stories/hi_wikipedia.txt

Adding Hindi language definition and a small sample book.

Add Hindi language definition and a small sample story.

---

lute/static/css/styles.css
lute/templates/read/index.html

Added a slider to turn pages. Turning pages with buttons as before still works. 
Bookmark button for page bookmarks created but hidden until implementation.

Read slider: slider to turn pages

---

lute/static/css/styles.css
lute/templates/book/tablelisting.html
tests/acceptance/book.feature
tests/acceptance/unsupported_parser.feature

Adds simple stats bar chart to the book listing:
> <img width="1559" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/5f32ce08-c076-4b6f-9a8b-4195fa0a9d8c">
Borrows a bunch of code from #110

Book listing stats

---

lute/book/forms.py
lute/book/model.py
lute/book/routes.py
lute/templates/book/create_new.html
tests/unit/book/test_Repository.py

Replacement PR for #153 
Addresses issue #155 
For discussion :-)

Add words per page field during book creation

---

lute/static/css/styles.css
lute/templates/book/tablelisting.html

Adjusted status bar for small views removing percentages below 2
Fixed book name wrapping

Booktable fixes

---

lute/static/css/styles.css
lute/static/css/tagify_overrides.css
lute/themes/css/Apple_Books.css
lute/themes/css/Dark_slate.css
lute/themes/css/Night.css

Form fields and other input types (including tagify fields and the new "words per page" field) styled to be visually consistent between one another

Consistent field styles

---

lute/static/js/lute.js
lute/templates/hotkeys.html
lute/templates/read/updated.html

Deals with issues #176 and #170, fixes #170.

Simplify lute js

---

lute/static/css/styles.css
lute/static/js/dict-tabs.js
lute/templates/read/index.html
lute/templates/term/_form.html
lute/templates/term/formframes.html

Made a DictTab class to contain all tab related info
Separated sentences and image lookup from standard tabs
Fixed menu list

DictTab class

---

lute/static/js/lute.js
lute/templates/read/index.html

`F` key now toggles focus mode

Focus mode shortcut

---

lute/db/demo/languages/czech.yaml
lute/db/schema/baseline.sql

Fix second embedded Czech dictionary not working

---

lute/themes/css/LWT.css
lute/themes/css/LingQ.css

Add LWT and LingQ themes

---

lute/static/css/styles.css
lute/static/js/resize.js

Dragging to resize the panes now works correctly on touch devices
Also added drag handle to the dictionary pane

Touch drag fix

---

lute/static/js/dict-tabs.js
lute/templates/read/index.html
lute/templates/term/_form.html
lute/templates/term/formframes.html

Addresses #288 
Can be merged once #289 is ok -- this branch builds off of that.

Issue 288 open first dict

---

lute/parse/space_delimited_parser.py
tests/conftest.py
tests/unit/parse/test_SpaceDelimitedParser.py

Issue 333: Remove zero-width joiner and non-joiner characters

---

.github/workflows/ci.yml
lute/__init__.py
lute/db/schema/baseline.sql
lute/db/schema/migrations_repeatable/trig_words.sql
lute/models/term.py
lute/read/render/renderable_calculator.py
lute/read/routes.py
lute/read/service.py
lute/static/js/lute.js
lute/templates/term/_form.html
lute/templates/termimport/index.html
lute/term/datatables.py
lute/term/forms.py
lute/term/model.py
lute/term/routes.py
lute/termimport/routes.py
lute/termimport/service.py
tests/acceptance/smoke.feature
tests/acceptance/sync_status.feature
tests/acceptance/test_smoke.py
tests/features/term_import.feature
tests/features/term_import_status_0.feature
tests/features/test_term_import.py
tests/orm/test_Term.py
tests/playwright/playwright.py
tests/unit/models/test_Term.py
tests/unit/read/test_service.py
tests/unit/term/test_Repository.py

Addresses #99, which in turn should clear up some inconsistent parsing people were running into during reading.
Draft PR for discussion and review, but I don't know if anyone can really review it!

Issue 99: store new terms on open page for reading

---

lute/templates/book/create_new.html
lute/templates/book/import_webpage.html
lute/templates/term/_form.html
lute/templates/termtag/_form.html

Add autofocus to forms

---

.github/workflows/ci.yml
lute/book/model.py
lute/db/demo.py
lute/language/routes.py
lute/language/service.py
lute/templates/index.html
lute/templates/language/list_predefined.html
scripts/dump_lang_data.py
tasks.py
tests/conftest.py
tests/playwright/playwright.py
tests/unit/book/test_Repository.py
tests/unit/db/test_demo.py
tests/unit/language/test_service.py

Several issues combined in this PR:
#275 
#392 
#394 
#395 
#399

Load language defs from submodule

---

lute/app_factory.py
lute/book/routes.py
lute/book/stats.py
lute/read/render/calculate_textitems.py
lute/read/render/multiword_indexer.py
lute/read/render/service.py
lute/settings/routes.py
lute/static/css/styles.css
lute/templates/book/tablelisting.html
requirements.txt
tests/unit/book/test_stats.py
tests/unit/read/render/test_multiword_indexer.py

Bookstats improvements

---

.github/workflows/ci.yml
README_PyPi.md
devstart.py
docker/Dockerfile
docker/docker-compose.yml.example
docker/docker_hub_overview.md
lute/main.py
tasks.py
tests/acceptance/book.feature
tests/acceptance/lute_test_client.py
tests/playwright/playwright.py

Issue 497: Change default port to 5001.

---

lute/book/model.py
lute/models/term.py
lute/read/routes.py
lute/static/css/styles.css
lute/static/js/lute.js
lute/templates/read/index.html
lute/templates/read/page_content.html
lute/templates/read/term_bulk_edit_form.html
lute/templates/read/term_edit_form.html
lute/templates/read/term_form_base.html
lute/templates/read/updated.html
lute/templates/term/_bulk_edit_form_fields.html
lute/templates/term/index.html
lute/term/model.py
lute/term/routes.py
lute/term/service.py
tests/acceptance/conftest.py
tests/acceptance/lute_test_client.py
tests/acceptance/reading.feature
tests/acceptance/term.feature
tests/unit/term/test_service.py

Add bulk term actions

---

lute/book/forms.py
lute/templates/book/create_new.html
lute/templates/book/edit.html

Add AAC, FLAC and WebM support
