lute/static/js/lute.js
This PR makes the following changes to /static/js/lute.js:
This function collects selected term elements, groups them by their `data_status_class` level, then submits them in batches to be updated with `update_status_for_elements`.
This function accepts a single argument `shiftBy`, an integer indicating the amount and direction to increment the status class as defined in the constant `validStatuses`.
Separating the selection of elements from the code that submits them to the server allows other functions to update statuses for different use cases. 
`update_status_for_elements` takes two arguments
- `new_status`: the status that will be set on the elements
- `elements`: a nodeList, array, or jQuery selection of elements to update
`update_selected_statuses` was doing a redundant selection …
=> fixes #33 - set a term(s) status via the keyboard

README.md
Changed the hyperlink to the discord invite link in the README.
=> Fixes #61 - Fix discord hyperlink in README

lute/static/css/styles.css, lute/templates/book/tablelisting.html
this fixes #57 by doing the following:
1. adds a class `book-title` to all book title links, so they can all be targeted easily with css
2. adds an empty placeholder in front of all `a.book-title` links so the indention is consistent
3. shows `tick.png` in the placeholder space on all `a.book-title.completed_book` links
4. adds a selector with good-but-not-perfect browser support* that removes indentation when the list contains zero completed books. On unsupported browsers the indent will remain even if there are no completed books.
* the `:has()` selector works in every modern browser, but firefox only added support in the most recent version (Dec, '23)
=> Move completed books checkmark on left, line up titles

lute/static/css/styles.css, lute/static/js/resize.js, lute/static/js/text-options.js, lute/templates/read/index.html
Ability to resize the left read pane and the right word and dict panes by dragging their borders.
Some code related to the "text width" functionality has been moved from `text-options.js` to the new `resize.js` file.
double click on the borders: for the main read pane it expands the read pane to 95% of the viewport width (but doesn't save this to the local storage). This is for temporarily expanding the pane if you do not need the dictionary for some time. Double clicking again (if the pane width is at 95%) gets it back to the previous width. 
For the right pane, double click expands the dictionary pane to 95% and the rest is the same as with the read pane.
=> Resize panes by dragging borders

.gitignore, lute/app_factory.py, lute/db/demo.py, lute/templates/index.html
A feature that @tg_kroening174 on Discord and I miss:
Dismissing the "_When you're done trying out the demo, [...]_" message without wiping the database clean.
I also added a `.gitignore` line for PyCharm project settings.
=> Exit demo mode option added

lute/templates/term/_form.html, lute/templates/term/formframes.html, lute/term/routes.py
Added delete term button in term form, visible in both `/read` and `/term/edit`:
Button in `/read` reloads the page
Button in `/term/edit` redirects to `/term/index`
Removed old delete button in `/term/edit`
Check if you're fine with the layout, I've placed the button below the "save" button, in the next table row.
This is the first JS code I have ever written lol, but it works.
=> Fix issue #13: Ability to delete a term from reading screen

lute/static/css/styles.css, lute/static/js/lute.js, lute/templates/read/index.html
Fixes the issue introduced after mobile view update. 
Main issue was that the tooltip was being created under the audio player if the word was close to the bottom of the page. Now it's created over the player. 
But a better solution would be detecting the audio player as the "end of the page" and showing the tooltip above the word.
=> Z-index order fix

lute/static/js/text-options.js, lute/templates/read/index.html
This PR fixes #111 by saving the scroll position and setting it back after `thetext` reload
Tested in Chrome and Firefox
=> Scroll to top after term save - fix

lute/templates/index.html
Fix spelling of "dismiss" in an anchor tag.
=> Fix spelling of "dismiss" in anchor tag for remove_demo_flag

lute/static/css/styles.css, lute/templates/book/tablelisting.html
Fixed the issue (introduced in the PR related to refresh all stats button) where Statuses column was getting distorted if browser window was narrower.
=> Booktable fix

lute/static/js/lute.js
In toggle highlight mode, cursor does not hover over the word but it still highlights it:
Fixed:
=> Fix toggle highlights classes are not removed when mouseout

lute/static/js/dict-tabs.js, lute/templates/read/index.html, lute/templates/term/_form.html, lute/templates/term/formframes.html
Addresses #289.
Add `LookupButton` static vars:
```
static TERM_FORM_CONTAINER = null;
static TERM_DICTS = null;
static LANG_ID = null;
```
The existing code creates global vars in a few places (either with let or const), and the LookupButton class uses these globals.  Declaring them static clarifies the intent of the variables, removes any ambiguity, and moves declaration into one place.
Many changed lines just add the LookupButton name to the var, eg `TERM_DICTS` becomes `LookupButton.TERM_DICTS`.
=> Issue 289 clarify js globals

lute/db/demo/languages/classical_chinese.yaml, lute/db/schema/baseline.sql
**Problem**: #16
The following script runs on the ctext.org so when the dictionary is embedded it redirects to the ctext.org
```js
if (top.location != self.location) { top.location = self.location; }
```
**Solutions**
- changing ctext.org to popup
- using another dictionary
**Alternative Dictionaries**
https://en.wiktionary.org/wiki/###
https://www.archchinese.com/chinese_english_dictionary.html?find=###
https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=1&wdqb=###
*https://www.xiaoma.info/hanzi.php?hz=###
**Fix**
I changed the dictionary to archchinese.
=> Fix Issue 16: clicking a word redirects to dictionary

lute/templates/read/index.html, lute/templates/read/reading_menu.html
=> Add ability to open a new Lute tab

lute/term/routes.py
=> Redirect user to /term/new when adding new term

lute/db/demo/languages/hindi.yaml, lute/db/schema/baseline.sql, lute/parse/space_delimited_parser.py, tests/unit/parse/test_SpaceDelimitedParser.py
Fixes #339 and mostly undoes #333 by restoring original space-delimited parser behavior and explicitly adding zero-width joiner and non-joiner characters to the language definitions for German and Hindi to make unit tests pass and demonstrate how to add zero-width joiner and non-joiner support to other languages.
This is the most conservative fix that retains the existing behavior in all other languages and only modifies the word-detection behavior of German and Hindi.
=> Issue 339 retain zero-width joiner and non-joiner characters

lute/static/css/styles.css
From issue #361 - the mobile css has a fair amount of whitespace which takes up real estate on smaller devices.  This PR proposes default changes to the css.  Here's a screenshot from my chrome devtools:
Before this change:
> <img width="384" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/3b5f0f35-14ca-481e-9863-f938021af63d">
After:
> <img width="401" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/65980f16-6761-40b4-b02d-a67a5d5822b9">
I think some people are already using mobile so opening this up for review (by @webofpies ) and others.
=> Issue 361: tighten up mobile css

lute/static/css/player-styles.css
added media query for even smaller viewports (#377) ![image](https://github.com/jzohrab/lute-v3/assets/70017511/001499d1-1e78-4935-b38b-99fc82b5b8e7)
=> Player styles for even smaller views

lute/templates/term/_form.html
- If the form is opened to create a new term and the language isn't set, focus should go there
-  If form is opened to create new and lang is set (b/c the user set the "current language" from home screen), focus goes to the term
- If lang and term are set, it should go to the translation.
=> Set focus for term form

lute/static/js/lute.js, lute/templates/term/_form.html
=> Remove autofocus cruft

lute/templates/language/_form.html
This addresses issue #391 to add a confirmation dialog box before navigating away from the language edit form.
It seemed pretty straight-forward so I threw this together. It just adds a "dirty" check like mentioned in the issue and forces a confirmation on the `beforeunload` event if any of the form fields have been changed.
Notably, I had to disable the popup for the save button as well as the delete button so it can use it's own (less generic) confirmation dialogue.
It passed all current tests, but I haven't added any new ones yet. Are there any particular smoke/acceptance tests you'd like me to add @jzohrab?
=> Add leave page confirmation dialog to language edit form

lute/app_factory.py, lute/bookmarks/datatables.py, lute/bookmarks/routes.py, lute/db/schema/baseline.sql, lute/db/schema/migrations/20240525_create_textbookmarks.sql, lute/models/book.py, lute/templates/bookmarks/list.html, lute/templates/read/index.html, lute/templates/read/reading_menu.html, tests/orm/test_Book.py, tests/orm/test_Text.py, tests/orm/test_TextBookmark.py, tests/playwright/playwright.py, tests/unit/textbookmark/test_datatables.py
This PR addresses issue #86 to add text bookmarks.
@jzohrab I'm pretty sure I've hit all the main requirements for the backend and smoke tests. Let me know if there's anything else I need to add or fixup before it would be ready to merge.
I think my next steps will probably be to add some demo data and maybe a mention of bookmarks in the Tutorial / Tutorial follow-up chapter and some basic acceptance tests.
I just wanted to get this PR posted before I lost steam :)
=> Add text bookmarks

lute/templates/stats/index.html
=> Add workaround for ChartJS shrinking chart bug

lute/static/css/styles.css, lute/static/js/dict-tabs.js, lute/templates/read/index.html
This PR addresses part of issue #379.
As mentioned in the comments, some dictionaries can steal focus from the reading pane making it impossible to use the left/right arrow keys to traverse words without regularly readjusting the focus.
The other component of the mentioned issue which involved automatically auto-focusing fields in the edit term form are not addressed. I agree with the analysis that it probably won't work with the existing workflow. I also don't think the default behavior should necessarily be to expect edits. Personally I mostly use the lookup pane for dictionary lookups and only rarely make edits to terms, so auto-focusing any of the edit fields would go against that workflow.
Regarding the solution to the focus stealing, I've reworked the activation of each dictionary …
=> Prevent dictionary tabs from stealing focus

lute/app_factory.py
Disable main page cache to always do pending book stat recalculations.
Seeing if this is a simpler approach than #461, which tries to do the same thing with javascript, but runs into some acceptance test problems.
=> Never cache main page

lute/templates/term/_form.html, tests/acceptance/conftest.py, tests/acceptance/lute_test_client.py
=> Issue 324 pending parent tag

lute/book/model.py, lute/cli/commands.py, lute/cli/import_books.py, lute/models/book.py, tests/unit/cli/test_import_books.py
This adds a command-line tool to bulk-import books from a CSV file.
The CSV file must have have a header row and contain specific columns which map to the properties of a book. For details, see the help for the new command:
```
flask --app lute.app_factory cli import_books_from_csv --help
```
=> Add CLI tool to bulk import books from a CSV file.

lute/static/css/styles.css, lute/static/js/lute.js, lute/templates/read/index.html, lute/templates/read/reading_menu.html
Adds an entry to the reading menu so that clicking on an Unknown term sets it to status 1 without opening the form.
> <img width="200" alt="image" src="https://github.com/user-attachments/assets/a919be96-ffb5-4475-a243-42eff786efd0" />
The "Tap sets status 1" is a bit cryptic, but there's limited real estate.  It may in fact be better to have this as a Setting, just to have more documentation there ... not sure.  Ah well.  First draft for discussion.
=> Add mobile option: tap Unknown word to set it to status 1.

lute/models/term.py, lute/static/css/styles.css, lute/static/js/lute-tagify-utils.js, lute/static/js/lute.js, lute/static/vendor/tagify/tagify_overrides.css, lute/templates/read/reading_menu.html, lute/templates/read/term_bulk_edit_form.html, lute/templates/term/_bulk_edit_form_fields.html, lute/templates/term/_form.html, lute/templates/term/index.html, lute/term/datatables.py, lute/term/routes.py, lute/term/service.py, tests/acceptance/lute_test_client.py, tests/playwright/playwright.py, tests/unit/term/test_datatables.py, tests/unit/term/test_service_apply_ajax_update.py, tests/unit/term/test_service_bulk_updates.py
Addresses #573.  Opening for full CI.
=> Iss 573 editable term listing

.gitignore, lute/bing/routes.py, lute/static/js/dict-tabs.js, lute/templates/imagesearch/index.html
This PR removes the template tags for images, and replaces them with a JS call once the DOM has loaded. Relates to #563 
Just wanted to push at this stage as:
1. This seems to work some of the time, but not always. I think I've narrowed it down to the Flask route `bing_search` because it seems like the images sources aren't always passed into the template
2. Would it be better if I looked at moving all of the parsing logic into the JS? Essentially porting the code below to JS. Maybe that's what you meant :-)
```python
search = urllib.parse.quote(text)
params = searchstring.replace("[LUTE]", search)
params = params.replace("###", search)  # TODO remove_old_###_placeholder: remove
url = "https://www.bing.com/images/search?" + params
content = ""
error_msg = ""
try:
with …
```
=> Make Bing search asynchronous
